mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns: list = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path
from .views import index, detail, results, vote

app_name: str = 'polls'

urlpatterns: list = [
    path('', index, name='index'),
    path('<int:question_id>/', detail, name='detail'),
    path('<int:question_id>/results', results, name='results'),
    path('<int:question_id>/vote', vote, name='vote')
]

polls/models.py
import datetime

from django.db.models import (
    Model,
    CharField,
    DateTimeField,
    ForeignKey,
    CASCADE,
    IntegerField,
    UniqueConstraint
)
from django.utils import timezone


class Question(Model):
    question_text: CharField = CharField(max_length=200)
    pub_date: DateTimeField = DateTimeField('date published')

    def __str__(self) -> str:
        return str(self.question_text)

    def was_published_recently(self) -> bool:
        now: datetime = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    class Meta:
        constraints: list[UniqueConstraint] = [
            UniqueConstraint(fields=['question_text'], name='unique_question')
        ]

class Choice(Model):
    question: ForeignKey = ForeignKey(Question, on_delete=CASCADE)
    choice_text: CharField = CharField(max_length=200)
    votes: IntegerField = IntegerField(default=0)

    def __str__(self) -> str:
        return str(self.choice_text)

    class Meta:
        constraints: list[UniqueConstraint] = [
            UniqueConstraint(fields=['question', 'choice_text'], name='unique_choice_per_question')
        ]

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpRequest, HttpResponse

from polls.models import Question

def _get_question_by_id(question_id: int) -> Question | Http404:
    return get_object_or_404(Question, pk=question_id)

def index(request: HttpRequest) -> HttpResponse:
    try:
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
    except Exception as err:
        raise Http404('Cannot retrieve question list') from err
    return render(request, 'polls/index.html', {'latest_question_list': latest_question_list})

def detail(request: HttpRequest, question_id: int) -> HttpResponse:
    return render(request, 'polls/detail.html', {'question': _get_question_by_id(question_id)})

def results(request: HttpRequest, question_id: int) -> HttpResponse:
    return render(request, 'polls/results.html', {'question': _get_question_by_id(question_id)})

def vote(request: HttpRequest, question_id: int) -> HttpResponse:
    return render(request, 'polls/vote.html', {'question': _get_question_by_id(question_id)})

polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Neuton:wght@700&display=swap"
  rel="stylesheet"
/>
<body>
  <section class="container">
    <h1>{{ question.question_text }}</h1>
    <ul class="question-list">
      {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
      {% endfor %}
    </ul>
    <div class="button-center">
      <button onclick="history.back()">Back</button>
    </div>
  </section>
</body>

polls/templates/polls/details.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Neuton:wght@700&display=swap"
  rel="stylesheet"
/>
<body>
  <section class="container">
    <h1>{{ question.question_text }}</h1>
    <ul class="question-list">
      {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
      {% endfor %}
    </ul>
    <div class="button-center">
      <button onclick="history.back()">Back</button>
    </div>
  </section>
</body>

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Neuton:wght@700&display=swap"
  rel="stylesheet"
/>
<body>
  <section class="container">
    <h1>Check out the polls below!</h1>
    {% if latest_question_list %}
    <ul class="question-list">
      {% for question in latest_question_list %}
      <li>
        <a href="{% url 'polls:detail' question.id %}"
          >{{ question.question_text }}</a
        >
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </section>
</body>

polls/templates/polls/results.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Neuton:wght@700&display=swap"
  rel="stylesheet"
/>
<body>
  <section class="container">
    <h1>Vote Results!</h1>
    <h2>Question: {{ question.question_text }}</h2>
    <h3>Check back later for results!</h3>
    <div class="button-center">
      <a id="to-homepage" href="{% url 'polls:index' %}">
        <button>Back</button>
      </a>
    </div>
  </section>
</body>

polls/templates/polls/vote.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Neuton:wght@700&display=swap"
  rel="stylesheet"
/>
<body>
  <section class="container">
    <h1>You are voting for:</h1>
    <h2>{{ question.question_text }}</h2>
    <h3>Check back later to vote!</h3>
    <div class="button-center">
      <a id="to-homepage" href="{% url 'polls:index' %}">
        <button>Back</button>
      </a>
    </div>
  </section>
</body>